/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.model.Contato;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felix Petiz Bonilho
 */
public class ExemploComboBox extends javax.swing.JFrame {

    //Cria variável auxiliar (possui o modelo de dados que servirá para conter os dados que serão adicionados em uma combobox)
    private DefaultComboBoxModel<Contato> modeloContato = new DefaultComboBoxModel<>();
    
    /**
     * Creates new form ExemploComboBox
     */
    public ExemploComboBox() {
        initComponents();
        
        //Relaciona nosso modeloContato com a ComboBox
        cbObjetos.setModel(modeloContato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        cbString = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        lblString = new javax.swing.JLabel();
        lblObjetos = new javax.swing.JLabel();
        cbObjetos = new javax.swing.JComboBox<>();
        btnInsereString = new javax.swing.JButton();
        btnInsereObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        cbString.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStringItemStateChanged(evt);
            }
        });

        lblString.setText("String");

        lblObjetos.setText("Objetos");

        cbObjetos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbObjetosItemStateChanged(evt);
            }
        });

        btnInsereString.setText("Insere String");
        btnInsereString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsereStringActionPerformed(evt);
            }
        });

        btnInsereObjeto.setText("Insere Objeto");
        btnInsereObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsereObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbString, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblString, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObjetos)
                            .addComponent(cbObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsereString)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsereObjeto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsereString)
                    .addComponent(btnInsereObjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblString)
                    .addComponent(lblObjetos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsereStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsereStringActionPerformed
        cbString.addItem(txtNome.getText());
        
        txtNome.setText("");
        txtNome.requestFocus();
    }//GEN-LAST:event_btnInsereStringActionPerformed

    private void btnInsereObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsereObjetoActionPerformed
        //Adiciona o contato no modelo da combo (para exibir as informações corretas é preciso
        //Sobrescrever o método toString() na classe Contato
        modeloContato.addElement(new Contato(txtNome.getText(), "(11)98811-0923"));
        
        txtNome.setText("");
        txtNome.requestFocus();
    }//GEN-LAST:event_btnInsereObjetoActionPerformed

    /**
     * Evento disparado quando um item da ComboBox é selecionado
     * @param evt 
     */
    private void cbStringItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStringItemStateChanged
        //Pega sobre o disparo do evento da seleção do novo item
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            //Captura o objeto que está selecionado
            //String s = cbString.getItemAt(cbString.getSelectedIndex());
            //ou por ser String
            String s = cbString.getSelectedItem().toString();
            
            JOptionPane.showMessageDialog(rootPane, "Item Selecionado: " + s, "Mensagem ao Usuário",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cbStringItemStateChanged

    private void cbObjetosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbObjetosItemStateChanged
        //Pega sobre o disparo do evento da seleção do novo item
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            //Captura o objeto que está selecionado
            //Contato c = modeloContato.getElementAt(cbObjetos.getSelectedIndex());
            //ou
            //Contato c = cbObjetos.getElementAt(cbObjetos.getSelectedIndex());
            //ou
            //Contato c = (Contato)modeloContato.getSelectedItem();
            //ou
            Contato c = (Contato)cbObjetos.getSelectedItem();
            
            JOptionPane.showMessageDialog(rootPane, "Item Selecionado: " + c.getNome() + "\n" + c.listaTelefones(), 
                    "Mensagem ao Usuário", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cbObjetosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsereObjeto;
    private javax.swing.JButton btnInsereString;
    private javax.swing.JComboBox<Contato> cbObjetos;
    private javax.swing.JComboBox<String> cbString;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetos;
    private javax.swing.JLabel lblString;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
